### PR TITLE
Add automatic Windows builds with AppVeyor CI

### PR DESCRIPTION
**Pull request by EwoutH**
Add AppVeyor CI to 360tools. The `.vcproj` and `.sln` are build with Visual Studio and artifacts are uploaded to AppVeyor. See example here: https://ci.appveyor.com/project/EwoutH/360tools

Also adds a Build Status badge to the Readme.

Travis only needs to be activated on https://ci.appveyor.com/project/Samsung/360tools or on https://github.com/marketplace/appveyor

### CODE REVIEW

**Comment by EwoutH** [comment]
@vladZakharchenko @ulsiguya @nolyn @minjung978 What do you guys think? :)

**Comment by nolyn** [comment]
Looks nice. I'm not sure many people are still using this software though. I'm not, I switched to the commonly developed 360Lib.

**Comment by EwoutH** [comment]
@vladZakharchenko @ulsiguya @minjung978 Any chance one of you can review this PR? Would be nice to merge it!

**Comment by EwoutH** [comment]
@vladZakharchenko @nolyn @minjung978 Closing this PR for now, please let me know if you would like this reopend and rebased.

**Pull request closed without merging**
