### PR TITLE
fix in erp 2 cmp conversion

### PR DESCRIPTION
**Pull request by nolyn**
h_out should be dividable by 3, not 4

### CODE REVIEW

**Comment by kpchoi** [comment]
"hout%4 != 0" is for checking of power of 2 of output image. it's not for geometry checking.

**Review by kpchoi — COMMENTED** [review]
"hout%4 != 0" is for checking of power of 2 of output image. it's not for geometry checking.

**Comment by nolyn** [comment]
I don't understand. Your recommended output image size for CMP:
CMP       3840x2880

math.log(3840,2)
11.906890595608518
math.log(2880,2)
11.491853096329676

As you can see, neither width nor height are a power of 2. I also tested the change I made. I allows more resolutions to be chosen. For example:

360tools_conv -i AerialCity_3840x1920_30fps_8bit_420_erp.yuv -w 3840 -h 1920 -f 3 -l 3832 -m 2874 -x 1 -y 1 -o AerialCity_3832x2874_30_8bit_420_cmp.yuv -n 10

The output video looks fine.

**Comment by kpchoi** [comment]
hi, nolyn, I did write typo in previouse comment, "%4" is for checking multiple of 4, not power of 2.
reolution of multiple of 4 can give good optimization by using simd tech and avoid corner case.
I hope for you to make sense.

**Comment by vladZakharchenko** [comment]
nolyn, in the expression
```
((w_out%4 != 0 || h_out%4 != 0) || (w_out*3 != h_out*4))) 
```
first part checks if the output is multiple of 4 for the reason mentioned by ulsiguya before,
whereas the second part verifies aspect ratio for unfolded cube map layout

**Review by vladZakharchenko — CHANGES_REQUESTED** [review]
Original intent of multiple of 4 is to provide SIMD optimization in future

**Comment by kpchoi** [comment]
I think explanation is enough for now. I hope to close this PR.
Thanks all.

**Pull request closed without merging**
